language: node_js
node_js:
  - '4.3'
env:
  global:
    secure: "KdQLRLYm7mKnbrWTuJ3kQAo217OLo7b5bfV9hB3daMRLhX9RpZrTEL6WQG4GotrodJgrHGXuH2PiMg7iypKoIkUkg6w8OvdMx5dFSgIbCnfjoeHwkbdXpb0ihZLeqXZpivfz1sT/3J7zvuAE9zqIllGJSjChYZjj4myIhamm10gp2EM+OZLH47EnP5RiZ1flDZgvRIEkIQc3MexZ5JxL90NqqfvvbZqSXGtt2Pw2//EdlppiDYc1s8zhabcRHBI3VyHJwqrGVSgAFCrvsV1C56L+TpiJtLXxsunTrF1iEDr9Cx5E9gmUbJiAQNnR0Dhtkhu3GlR5Bw1nVJrB/iRcjjzFD51y5Lypssu07Ew69oZY6ZPlhYw6Q+LX8A73+Lhh1Iygn+n3p8R3unQ1Qa7tf/sn7bL3fv6WBXRJjWeVjtEEp3oNNU3HECAdABp8ibqKobl6jL3O/m77Xy2xVHIb9wU7jJ0tCjcjVW2a9GAYwbz8g9MbLrkaTxUSwhqT0DGVOwEkU/qPIVJ5GImELc4ePdzsFSK1OJA2Vbn/enBY0ka1eZ0pfzVmIOADFbMu8IoI30Jyo/5rpKj2bESqDTgW/1emu24ODuUQWlR+gY77kJj2hjxCjfeGLLWssKuwJt9m9FqiXZeUXyypBr7gBf38bbUN7quTPXL1CViCKZfJ4nY="

services:
  - mysql

install:
  - npm install -g typescript
  - npm install

before_script:
  - mysql -uroot -e "create database travis_test"
  - tsc

script:
   - echo 'Do nothing.'
#  - npm test

after_success:
  - npm install -g serverless
  - npm install
  - echo $SLS_DEBUG
  - sls deploy --stage prod


deploy:
  provider: script
  script: chmod +x ./travis-deploy.sh && echo $AWS_ACCESS_KEY_ID && echo hello.. && ./travis-deploy.sh
  skip_cleanup: true
  on:
    branch: master

