language: node_js
node_js:
  - '4.3'
env:
  global:
  - DATABASE_URL=mysql://root@localhost/travis_test
  - secure: oeixlIYofhq8vSIrU5LTRMBpgVIr8RUQsdrnve8x+u700Pzeb/IxM+rY9wFDvqOrKqPWpR6u0QFj04Xg/WARPdSa+wcjiZ62Fw1Ad2B/3gJJQOZ66ouifONWhHZPnUKusEX2Q/7EmRTwFgvSBsxGfkEhspvpuyo7WAZ4AwWxfGByFd/3aGIfOhwQpXwePwK97XuprLt7sJsraxt9C/t/J9dUEGOpNA5MUqwZftzKDMDKd6RrNnAJWUgCnnM79MIFgRgk22EC2qWztX8IZm8BSL2v8KqR9+Phal19oJx0ehd/NQ7fEhHKnFxa5Kbs1UcUi5+pIEj2euLgWT7QUl4cxBTa3LcirL44PiOhE78WTI1b7b7PVf8AAn8KIKIUU9DSnq0i6SADyjtGGVhUzIuKj+edQCjOUIH4E2qP6iNX+TabQucPnJkkRHnlk+5ifznWecHKt//Os0kzaEKce1+z98VOrvHgEAhYiKch/5QVLn8heyfvM5flZBGOmLUBxWNI3uE05Gef6Uz5MLIxuEZcpN7WxHjkllGx0V4W81Szd3NPmrjicXhAfTqI3ZtX91y564UjsXx5ApIrhEHzTh7cfeaW/6VSHvs4hVn5mbUP8Tae0kykImLvVMaQAGUggpojsnhzUnxJGK1j4QZzLm1HOqkZdAy9TIP5wDj6VuqbVkc=
  - secure: WAzs06luSq3EBBKPiy6uZizGPkAxuXc6ZyLBFZzefD8E4Jn0UqJs8mr7oth1ZhTRC+zXnKaz70LRleakjEZqkdjkaY4+O6cwNlOI9Zswl1+H1N8913YZtSt08KbXA4bxWdbknJ4565FHlD/Wv0xqTmx3F+nNL/kLlKtMGhe6DZwnkAE3ANZHcudJLntpSUcCD2vEDL6yFliXUkOCspntSjauL0BMSe73VHnINy1sI7lWR28olt3PKb72MkkCyz+FPa96yoanZOt0SJvieN+n+oF/xrdH8q1abUGXAJzk2JJeJUBvTcQRQPQ8HnbqGQpEEl0WfAwma8lcOiOciOB5iHXysClN261B+hkKHB6w1QNrylEtdxXM5kYoBZV3v5IgRhCqNwNVSQQxQdvYlLvu7/mwHmGOCUTaM0Z0YodehQZUfAC62ugp6rVtgxBLnW+ap4NcL7S7SWfXl4acH/I9EZ3XZGcKgEiotAEDKkXGWEtR/Vh+iueak/uqpvAKrHXlK817peI7XhmaP3KwJkKjZmi/1kXSmLvxK+lmX/h7NjRdETceUDrXrktJ9Q8tKS41ABkKCHxIxbXdBcWjPbBd363C7+wQWcnXVTln7TgP8a+z1E13Q4Q2Y7o0O7+xPsBzj2arhWS8vdxQ6hrOCJT6k7ppBiARE3AZGnXiZoajCAA=

services:
  - mysql

install:
  - npm install -g typescript
  - npm install

before_script:
  - mysql -uroot -e "create database travis_test"
  - tsc

script:
  - npm test

deploy:
  provider: script
  script: chmod +x ./travis-deploy.sh && ./travis-deploy.sh
  skip_cleanup: true
  on:
    branch: master

