language: node_js
node_js:
  - "4.3"
env:
  global:
    - DATABASE_URL=mysql://root@localhost/travis_test

install:
  - npm install -g typescript
  - npm install

before_script:
  - mysql -uroot -e "create database travis_test"
  - tsc

script:
  - npm test

