version: 0.1

phases:
  install:
    commands:
      - sudo apt-get install mysql-server
      - mysql --version
      - mysqladmin -u root password rootPass0
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - npm test

artifacts:
  type: zip
  files:
    - test.js
